// <auto-generated />
using System;
using FeuerwehrUpdates.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeuerwehrUpdates.Migrations
{
    [DbContext(typeof(FWUpdatesDbContext))]
    partial class FWUpdatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("FeuerwehrUpdates.DTOs.KeysDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("p256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("FeuerwehrUpdates.DTOs.SubscriptionDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpirationTime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KeysId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeysId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("FeuerwehrUpdates.DTOs.SubscriptionDTO", b =>
                {
                    b.HasOne("FeuerwehrUpdates.DTOs.KeysDTO", "Keys")
                        .WithOne("Subscription")
                        .HasForeignKey("FeuerwehrUpdates.DTOs.SubscriptionDTO", "KeysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keys");
                });

            modelBuilder.Entity("FeuerwehrUpdates.DTOs.KeysDTO", b =>
                {
                    b.Navigation("Subscription")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
